---@class BufhopperNextKeyContext
---@field config BufhopperConfig
---@field mapped_keys table<string, integer>
---@field keyset string[]
---@field prev_key string | nil
---@field key_index integer
---@field file_name string

---@class BufhopperBufferKeymapping
---@field key string
---@field buf integer
---@field file_name string
---@field file_path string
---@field file_path_tokens string[]
---@field buf_indicators string
